#include <stdint.h>
#include <sys/types.h>
#include <orbis/_types/kernel.h>
#include <orbis/_types/pthread.h>
#include <orbis/_types/errors.h>

#ifndef _SCE_KERNEL_H_
#define _SCE_KERNEL_H_

#ifdef __cplusplus 
extern "C" {
#endif

extern uint64_t sceLibcHeapSize;
extern uint32_t sce_libc_heap_delayed_alloc;
extern uint32_t sce_libc_heap_extended_alloc;

struct Proc_Stats
{
	int32_t lo_data;								//0x00
	uint32_t td_tid;						//0x04
	OrbisKernelTimespec user_cpu_usage_time;	//0x08
	OrbisKernelTimespec system_cpu_usage_time;  //0x18
}; //0x28

int32_t sceKernelDebugOutText(int32_t dbg_channel, const char* text, ...);
int32_t sceKernelGetThreadName(uint32_t id, char* out);
int32_t sceKernelGetCpuUsage(struct Proc_Stats* out, int32_t* size);
uint64_t sceKernelGetCpuFrequency();
int32_t sceKernelAddFileEvent(OrbisKernelEqueue, int32_t, int32_t, void*);
int32_t sceKernelAddHRTimerEvent(OrbisKernelEqueue, int32_t, OrbisKernelTimespec*, void*);
int32_t sceKernelAddReadEvent(OrbisKernelEqueue, int32_t, size_t, void*);
int32_t sceKernelAddTimerEvent(OrbisKernelEqueue, int32_t, OrbisKernelUseconds, void*);
int32_t sceKernelAddUserEvent(OrbisKernelEqueue, int);
int32_t sceKernelAddUserEventEdge(OrbisKernelEqueue, int);
int32_t sceKernelAddWriteEvent(OrbisKernelEqueue, int32_t, size_t, void*);
int32_t sceKernelAllocateDirectMemory(off_t, off_t, size_t, size_t, int32_t, off_t*);
int32_t sceKernelAllocateMainDirectMemory(size_t, size_t, int32_t, off_t*);
int32_t sceKernelAvailableDirectMemorySize(off_t, off_t, size_t, off_t, size_t);
int32_t sceKernelAvailableFlexibleMemorySize(size_t*);
void sceKernelBacktraceSelf();
int32_t sceKernelBatchMap(void*, int, int*);
int32_t sceKernelBatchMap2(void*, int, int*, int);
int32_t sceKernelCancelEventFlag(OrbisKernelEventFlag, uint64_t, int32_t*);
int32_t sceKernelCancelSema(OrbisKernelSema, int32_t, int32_t*);
void sceKernelCheckedReleaseDirectMemory(off_t memstart, size_t memlen);
int sceKernelCheckReachability(char*);
int32_t sceKernelChmod(const char *path, OrbisKernelMode mode);
int32_t sceKernelClearEventFlag(OrbisKernelEventFlag, uint64_t);
void sceKernelClearGameDirectMemory();
void sceKernelClockGetres();
void sceKernelClockGettime();
int32_t sceKernelClose(int32_t);
int32_t sceKernelCloseEventFlag(void* event);
void sceKernelCloseSema();
void sceKernelConvertLocaltimeToUtc();
void sceKernelConvertUtcToLocaltime();
int32_t sceKernelCreateEqueue(OrbisKernelEqueue*, const char*);
int32_t sceKernelCreateEventFlag(OrbisKernelEventFlag*, const char*, uint32_t, uint64_t, const OrbisKernelEventFlagOptParam*);
int32_t sceKernelCreateSema(OrbisKernelSema*, const char*, uint32_t, int32_t, int32_t, const OrbisKernelSemaOptParam*);
void sceKernelDebugGetAppStatus();
void sceKernelDebugGpuPaDebugIsInProgress();
void sceKernelDebugRaiseException();
void sceKernelDebugRaiseExceptionOnReleaseMode();
int32_t sceKernelDeleteEqueue(OrbisKernelEqueue); 
int32_t sceKernelDeleteEventFlag(OrbisKernelEventFlag);
int32_t sceKernelDeleteFileEvent(OrbisKernelEqueue, int);
int32_t sceKernelDeleteHRTimerEvent(OrbisKernelEqueue, int);
int32_t sceKernelDeleteReadEvent(OrbisKernelEqueue, int);
int32_t sceKernelDeleteSema(OrbisKernelSema);
int32_t sceKernelDeleteTimerEvent(OrbisKernelEqueue, int);
int32_t sceKernelDeleteUserEvent(OrbisKernelEqueue, int);
int32_t sceKernelDeleteWriteEvent(OrbisKernelEqueue, int);
int32_t sceKernelDirectMemoryQuery(off_t, int32_t, void *, size_t);
int32_t sceKernelDlsym(int32_t handle, const char *symbol, void **address);
void sceKernelError();
void sceKernelEventLogInit();
void sceKernelEventLogPread();
void sceKernelEventLogWrite();
int32_t sceKernelFchmod(int32_t, OrbisKernelMode);
int32_t sceKernelFcntl(int32_t, int32_t, ...);
void sceKernelFlock();
int32_t sceKernelFstat(int32_t, OrbisKernelStat*);
int32_t sceKernelFsync(int32_t);
int32_t sceKernelFtruncate(int32_t, off_t);
int32_t sceKernelFutimes(int32_t, const OrbisKernelTimeval *);
void sceKernelGetAllowedSdkVersionOnSystem();
int32_t sceKernelGetAppInfo(pid_t pid, OrbisAppInfo* info);
void sceKernelGetBackupRestoreMode();
int32_t sceKernelGetCompiledSdkVersion(int32_t*);
void sceKernelGetCompiledSdkVersionByPid();
int32_t sceKernelGetCpumode(void);
int32_t sceKernelGetCurrentCpu(void);
void sceKernelGetDataTransferMode();
int32_t sceKernelGetdents(int32_t, char *, int);
size_t sceKernelGetDirectMemorySize();
int32_t sceKernelGetDirectMemoryType(off_t, int32_t *, off_t *, off_t *);
int32_t sceKernelGetdirentries(int32_t, char *, int32_t, int64_t *);
intptr_t sceKernelGetEventData(const OrbisKernelEvent*);
int32_t sceKernelGetEventError(const OrbisKernelEvent*);
uint32_t sceKernelGetEventFflags(const OrbisKernelEvent*);
int32_t sceKernelGetEventFilter(const OrbisKernelEvent*);
uintptr_t sceKernelGetEventId(const OrbisKernelEvent*);
void* sceKernelGetEventUserData(const OrbisKernelEvent*);
const char * sceKernelGetFsSandboxRandomWord(void);
uint64_t sceKernelGetGPI(void);
void sceKernelGetGPO();
void sceKernelGetIdPs(void* ret);
void sceKernelGetIpcPath();
int32_t sceKernelGetModuleInfo(OrbisKernelModule handle, OrbisKernelModuleInfo* info);
int32_t sceKernelGetModuleInfoForUnwind(void* addr, uint32_t flags, OrbisKernelModuleInfoForUnwind* info);
int32_t sceKernelGetModuleInfoFromAddr(void* addr, uint32_t flags, OrbisKernelModuleInfoEx* info);
int32_t sceKernelGetModuleInfoInternal(OrbisKernelModule handle, OrbisKernelModuleInfoEx* info);
int32_t sceKernelGetModuleList(OrbisKernelModule *array, size_t size, size_t *available);
int32_t sceKernelGetOpenPsIdForSystem(void* ret);
int32_t sceKernelGetPageTableStats(int32_t *, int32_t*, int32_t*, int32_t*);
uint64_t sceKernelGetProcessTime(void);
uint64_t sceKernelGetProcessTimeCounter(void);
uint64_t sceKernelGetProcessTimeCounterFrequency(void);
void sceKernelGetProcParam();
int32_t sceKernelGetPrtAperture(int32_t, void **, size_t *);
void sceKernelGetSubsysId();
void sceKernelGetSystemSwBeta();
int32_t sceKernelGetSystemSwVersion(OrbisKernelSwVersion *version);
int32_t sceKernelGettimeofday(OrbisKernelTimeval *timeValue);
void sceKernelGettimezone();
uint64_t sceKernelGetTscFrequency(void);
int32_t sceKernelHasNeoMode(void);
int32_t sceKernelHwHasOpticalOut(void);
void sceKernelIccControlBDPowerState();
void sceKernelIccGetCpuInfoBit();
void sceKernelIccGetPowerNumberOfBootShutdown();
void sceKernelIccGetPowerOperatingTime();
void sceKernelIccGetPowerUpCause();
void sceKernelIccGetThermalAlert();
void sceKernelIccIndicatorBootDone();
void sceKernelIccIndicatorShutdown();
void sceKernelIccIndicatorStandby();
void sceKernelIccIndicatorStandbyBoot();
void sceKernelIccIndicatorStandbyShutdown();
void sceKernelIccNotifyBootStatus();
// sceKernelIccNvsFlush = (DANGER / DO NOT USE THIS UNLESS YOU KNOW EXACTLY WHAT YOUR DOING, COULD RESULT IN A PERMA BRICK)
void sceKernelIccNvsFlush();
void sceKernelIccReadPowerBootMessage();
void sceKernelIccSetBuzzer(int32_t mode);
void sceKernelIccSetCpuInfoBit();
void sceKernelInternalHeapPrintBacktraceWithModuleInfo();
void sceKernelInternalMemoryGetModuleSegmentInfo();
int32_t sceKernelIsAuthenticNeo(void);
int32_t sceKernelIsCEX(void);
int32_t sceKernelIsDevKit(void);
int32_t sceKernelIsGenuineN(void);
int32_t sceKernelIsInSandbox(void);
int32_t sceKernelIsKratos(void);
int32_t sceKernelIsNeoMode(void);
int32_t sceKernelIsStack(void *, void **, void **);
int32_t sceKernelIsTestKit(void);
void sceKernelJitCreateAliasOfSharedMemory();
void sceKernelJitCreateSharedMemory();
void sceKernelJitGetSharedMemoryInfo();
void sceKernelJitMapSharedMemory();
uint32_t sceKernelLoadStartModule(const char *, size_t, const void *, uint32_t, void *, void *);
off_t sceKernelLseek(int32_t, off_t, int);
int32_t sceKernelLwfsAllocateBlock(int32_t, off_t);
off_t sceKernelLwfsLseek(int32_t, off_t, int);
int32_t sceKernelLwfsSetAttribute(int32_t, int);
ssize_t sceKernelLwfsWrite(int32_t, const void *, size_t);
int32_t sceKernelMapDirectMemory(void**, size_t, int32_t, int32_t, off_t, size_t);
int32_t sceKernelMapDirectMemory2(void **, size_t, int32_t, int32_t, int32_t, off_t, size_t);
int32_t sceKernelMapFlexibleMemory(void **, size_t, int32_t, int);
int32_t sceKernelMapNamedDirectMemory(void **, size_t, int32_t, int32_t, off_t, size_t, const char *);
int32_t sceKernelMapNamedFlexibleMemory(void **, size_t, int32_t, int32_t, const char *);
void sceKernelMapNamedSystemFlexibleMemory();
int32_t sceKernelMkdir(const char *path, OrbisKernelMode mode);
void sceKernelMlock();
void sceKernelMlockall();
int32_t sceKernelMmap(void *, size_t, int32_t, int32_t, int32_t, off_t, void **);
int32_t sceKernelMprotect(const void *, size_t, int);
int32_t sceKernelMsync(void *, size_t, int);
int32_t sceKernelMtypeprotect(const void *, size_t, int32_t, int);
void sceKernelMunlock();
void sceKernelMunlockall();
int32_t sceKernelMunmap(void *, size_t);
int32_t sceKernelNanosleep(const OrbisKernelTimespec *, OrbisKernelTimespec *);
int32_t sceKernelOpen(const char *, int32_t, OrbisKernelMode);
int32_t sceKernelOpenEventFlag(void* event, const char* name);
void sceKernelOpenSema();
int32_t sceKernelPollEventFlag(OrbisKernelEventFlag, uint64_t, uint32_t, uint64_t*);
int32_t sceKernelPollSema(OrbisKernelSema, int);
size_t sceKernelPread(int32_t, void *, size_t, off_t);
size_t sceKernelPreadv(int32_t, const OrbisKernelIovec *, int32_t, off_t);
void sceKernelPrintBacktraceWithModuleInfo();
size_t sceKernelPwrite(int32_t, const void *, size_t, off_t);
size_t sceKernelPwritev(int32_t, const OrbisKernelIovec *, int32_t, off_t);
int32_t sceKernelQueryMemoryProtection(void *, void **, void **, int32_t *);
void sceKernelRdup();
size_t sceKernelRead(int32_t, void *, size_t);
uint64_t sceKernelReadTsc(void);
size_t sceKernelReadv(int32_t, const OrbisKernelIovec *, int);
void sceKernelReboot();
int32_t sceKernelReleaseDirectMemory(off_t, size_t);
int32_t sceKernelReleaseFlexibleMemory(void *, size_t);
int32_t sceKernelRename(const char *oldfilename, const char *newfilename);
void sceKernelReportUnpatchedFunctionCall();
int32_t sceKernelReserveVirtualRange(void **, size_t, int32_t, size_t);
int32_t sceKernelRmdir(const char *folder);
int32_t sceKernelSendNotificationRequest(int32_t device, OrbisNotificationRequest* req, size_t size, int32_t blocking);
void sceKernelSetAppInfo();
void sceKernelSetBackupRestoreMode();
int32_t sceKernelSetCompressionAttribute(int32_t, int);
int32_t sceKernelSetEventFlag(OrbisKernelEventFlag, uint64_t);
int32_t sceKernelSetFsstParam(int32_t, void *);
void sceKernelSetGPI();
void sceKernelSetGPO();
void sceKernelSetProcessName();
int32_t sceKernelSetPrtAperture(int32_t, void *, size_t);
void sceKernelSetSafemode();
void sceKernelSettimeofday();
int32_t sceKernelSetVirtualRangeName(const void *, size_t, const char *);
void sceKernelSetVmContainer();
int32_t sceKernelSignalSema(OrbisKernelSema, int);
int32_t sceKernelSleep(uint32_t);
int32_t sceKernelStat(const char *, OrbisKernelStat *);
int32_t sceKernelStopUnloadModule(OrbisKernelModule, size_t, const void *, uint32_t, void *, int32_t *);
void sceKernelSwitchToBaseMode();
void sceKernelSwitchToNeoMode();
void sceKernelSync(void);
void sceKernelTerminateSysCore();
void sceKernelTitleWorkaroundIsEnabled();
void sceKernelTitleWorkdaroundIsEnabled();
int32_t sceKernelTriggerUserEvent(OrbisKernelEqueue, int32_t, void*);
int32_t sceKernelTruncate(const char *, off_t);
int32_t sceKernelUnlink(const char *);
int32_t sceKernelUsleep(uint32_t);
int32_t sceKernelUtimes(const char *, const OrbisKernelTimeval *);
int32_t sceKernelUuidCreate(OrbisKernelUuid*);
int32_t sceKernelVirtualQuery(const void *, int32_t, OrbisKernelVirtualQueryInfo *, size_t);
int32_t sceKernelWaitEqueue(OrbisKernelEqueue, OrbisKernelEvent*, int32_t, int32_t*, OrbisKernelUseconds*);
int32_t sceKernelWaitEventFlag(OrbisKernelEventFlag, uint64_t, uint32_t, uint64_t*, OrbisKernelUseconds*);
int32_t sceKernelWaitSema(OrbisKernelSema, int32_t, OrbisKernelUseconds*);
size_t sceKernelWrite(int32_t, const void *, size_t);
size_t sceKernelWritev(int32_t, const OrbisKernelIovec *);
void sceLibcMspaceCreateForMonoMutex();
void scePthreadAtfork();
int32_t scePthreadAttrDestroy(OrbisPthreadAttr*);
int32_t scePthreadAttrGet(OrbisPthread, OrbisPthreadAttr*);
int32_t scePthreadAttrGetaffinity(const OrbisPthreadAttr*, void*);
int32_t scePthreadAttrGetdetachstate(const OrbisPthreadAttr*, int32_t*);
int32_t scePthreadAttrGetguardsize(const OrbisPthreadAttr*, size_t*);
void scePthreadAttrGetinheritsched();
void scePthreadAttrGetschedparam();
void scePthreadAttrGetschedpolicy();
void scePthreadAttrGetscope();
int32_t scePthreadAttrGetstack(const OrbisPthreadAttr* __restrict, void** __restrict, size_t* __restrict);
int32_t scePthreadAttrGetstackaddr(const OrbisPthreadAttr*, void**);
int32_t scePthreadAttrGetstacksize(const OrbisPthreadAttr*, size_t*);
int32_t scePthreadAttrInit(OrbisPthreadAttr*);
int32_t scePthreadAttrSetaffinity(OrbisPthreadAttr*, uint64_t);
void scePthreadAttrSetcreatesuspend();
int32_t scePthreadAttrSetdetachstate(OrbisPthreadAttr*, int);
int32_t scePthreadAttrSetguardsize(OrbisPthreadAttr*, size_t);
void scePthreadAttrSetinheritsched(OrbisPthreadAttr*, int);
void scePthreadAttrSetschedparam(OrbisPthreadAttr*, struct sched_param*);
void scePthreadAttrSetschedpolicy();
void scePthreadAttrSetscope();
int32_t scePthreadAttrSetstack(OrbisPthreadAttr*, void*, size_t);
int32_t scePthreadAttrSetstackaddr(OrbisPthreadAttr*, void*);
int32_t scePthreadAttrSetstacksize(OrbisPthreadAttr*, size_t);
int32_t scePthreadBarrierattrDestroy(OrbisPthreadBarrierattr*);
void scePthreadBarrierattrGetpshared();
int32_t scePthreadBarrierattrInit(OrbisPthreadBarrierattr*);
void scePthreadBarrierattrSetpshared();
int32_t scePthreadBarrierDestroy(OrbisPthreadBarrier*);
int32_t scePthreadBarrierInit(OrbisPthreadBarrier*, const OrbisPthreadBarrierattr*, unsigned, const char*);
int32_t scePthreadBarrierWait(OrbisPthreadBarrier*);
int32_t scePthreadCancel(OrbisPthread);
int32_t scePthreadCondattrDestroy(OrbisPthreadCondattr*);
void scePthreadCondattrGetclock();
void scePthreadCondattrGetpshared();
int32_t scePthreadCondattrInit(OrbisPthreadCondattr*);
void scePthreadCondattrSetclock();
void scePthreadCondattrSetpshared();
int32_t scePthreadCondBroadcast(OrbisPthreadCond*);
int32_t scePthreadCondDestroy(OrbisPthreadCond*);
int32_t scePthreadCondInit(OrbisPthreadCond*, const OrbisPthreadCondattr*, const char*);
int32_t scePthreadCondSignal(OrbisPthreadCond*);
int32_t scePthreadCondSignalto(OrbisPthreadCond*, OrbisPthread);
int32_t scePthreadCondTimedwait(OrbisPthreadCond*, OrbisPthreadMutex*, OrbisKernelUseconds);
int32_t scePthreadCondWait(OrbisPthreadCond*, OrbisPthreadMutex*);
int32_t scePthreadCreate(OrbisPthread *, const OrbisPthreadAttr *, void*(*F)(void*), void *, const char *);
int32_t scePthreadDetach(OrbisPthread);
int32_t scePthreadEqual(OrbisPthread, OrbisPthread);
void scePthreadExit(void*);
void scePthreadGetaffinity(OrbisPthread, uint64_t*);
void scePthreadGetconcurrency();
int32_t scePthreadGetcpuclockid(OrbisPthread, clockid_t*);
int32_t scePthreadGetname(OrbisPthread, char*);
int32_t scePthreadGetprio(OrbisPthread, int32_t*);
void scePthreadGetschedparam();
void* scePthreadGetspecific(OrbisPthreadKey);
int32_t scePthreadGetthreadid(void);
int32_t scePthreadJoin(OrbisPthread, void**);
int32_t scePthreadKeyCreate(OrbisPthreadKey*, void(*destructor)(void*));
int32_t scePthreadKeyDelete(OrbisPthreadKey);
void scePthreadMain();
void scePthreadMulti();
int32_t scePthreadMutexattrDestroy(OrbisPthreadMutexattr*);
void scePthreadMutexattrGetkind();
int32_t scePthreadMutexattrGetprioceiling(OrbisPthreadMutexattr*, int32_t*);
int32_t scePthreadMutexattrGetprotocol(OrbisPthreadMutexattr*, int32_t*);
void scePthreadMutexattrGetpshared();
int32_t scePthreadMutexattrGettype(OrbisPthreadMutexattr*, int32_t*);
int32_t scePthreadMutexattrInit(OrbisPthreadMutexattr*);
void scePthreadMutexattrSetkind();
int32_t scePthreadMutexattrSetprioceiling(OrbisPthreadMutexattr*, int);
int32_t scePthreadMutexattrSetprotocol(OrbisPthreadMutexattr*, int);
void scePthreadMutexattrSetpshared();
int32_t scePthreadMutexattrSettype(OrbisPthreadMutexattr*, int);
int32_t scePthreadMutexDestroy(OrbisPthreadMutex*);
int32_t scePthreadMutexGetprioceiling(OrbisPthreadMutex*, int32_t*);
void scePthreadMutexGetspinloops();
void scePthreadMutexGetyieldloops();
int32_t scePthreadMutexInit(OrbisPthreadMutex*, const OrbisPthreadMutexattr*, const char*);
void scePthreadMutexIsowned();
int32_t scePthreadMutexLock(OrbisPthreadMutex*);
int32_t scePthreadMutexSetprioceiling(OrbisPthreadMutex*, int32_t, int32_t*);
void scePthreadMutexSetspinloops();
void scePthreadMutexSetyieldloops();
int32_t scePthreadMutexTimedlock(OrbisPthreadMutex*, OrbisKernelUseconds);
int32_t scePthreadMutexTrylock(OrbisPthreadMutex*);
int32_t scePthreadMutexUnlock(OrbisPthreadMutex*);
int32_t scePthreadOnce(OrbisPthreadOnce*, void(*init)(void));
int32_t scePthreadRename(OrbisPthread, const char*);
void scePthreadResume();
void scePthreadResumeAll();
int32_t scePthreadRwlockattrDestroy(OrbisPthreadRwlockattr*);
void scePthreadRwlockattrGetpshared();
int32_t scePthreadRwlockattrInit(OrbisPthreadRwlockattr*);
void scePthreadRwlockattrSetpshared();
int32_t scePthreadRwlockDestroy(OrbisPthreadRwlock*);
int32_t scePthreadRwlockInit(OrbisPthreadRwlock*, const OrbisPthreadRwlockattr*, const char*);
int32_t scePthreadRwlockRdlock(OrbisPthreadRwlock*);
int32_t scePthreadRwlockTimedrdlock(OrbisPthreadRwlock*, OrbisKernelUseconds);
int32_t scePthreadRwlockTimedwrlock(OrbisPthreadRwlock*, OrbisKernelUseconds);
int32_t scePthreadRwlockTryrdlock(OrbisPthreadRwlock*);
int32_t scePthreadRwlockTrywrlock(OrbisPthreadRwlock*);
int32_t scePthreadRwlockUnlock(OrbisPthreadRwlock*);
int32_t scePthreadRwlockWrlock(OrbisPthreadRwlock*);
OrbisPthread scePthreadSelf();
void scePthreadSetaffinity();
void scePthreadSetBesteffort();
int32_t scePthreadSetcancelstate(int32_t, int32_t*);
int32_t scePthreadSetcanceltype(int32_t, int32_t*);
void scePthreadSetconcurrency();
void scePthreadSetName();
int32_t scePthreadSetprio(OrbisPthread, int);
void scePthreadSetschedparam();
int32_t scePthreadSetspecific(OrbisPthreadKey, const void*);
void scePthreadSingle();
void scePthreadSuspend();
void scePthreadSuspendAll();
void scePthreadTestcancel(void);
void scePthreadTimedjoin();
void scePthreadYield(void);

// This is a redeclaration of the one used by FreeBSD, do not change this.
int ioctl(int fd, unsigned long request, ...);

#ifdef __cplusplus
}
#endif

#endif
