#ifndef _SCE_NET_H_
#define _SCE_NET_H_

#include <stdint.h>

#include <orbis/_types/net.h>

#ifdef __cplusplus 
extern "C" {
#endif

OrbisNetId sceNetAccept(OrbisNetId, OrbisNetSockaddr*, OrbisNetSocklen_t*);
void sceNetAllocateAllRouteInfo();
void sceNetBandwidthControlGetDefaultParam();
void sceNetBandwidthControlGetIfParam();
void sceNetBandwidthControlGetPolicy();
void sceNetBandwidthControlSetDefaultParam();
void sceNetBandwidthControlSetIfParam();
void sceNetBandwidthControlSetPolicy();
int32_t sceNetBind(OrbisNetId, const OrbisNetSockaddr*, OrbisNetSocklen_t);
void sceNetClearDnsCache();
void sceNetConfigAddArp();
void sceNetConfigAddIfaddr();
void sceNetConfigAddMRoute();
void sceNetConfigAddRoute();
void sceNetConfigAddRoute6();
void sceNetConfigCleanUpAllInterfaces();
void sceNetConfigDelArp();
void sceNetConfigDelDefaultRoute();
void sceNetConfigDelDefaultRoute6();
void sceNetConfigDelIfaddr();
void sceNetConfigDelIfaddr6();
void sceNetConfigDelMRoute();
void sceNetConfigDelRoute();
void sceNetConfigDelRoute6();
void sceNetConfigDownInterface();
void sceNetConfigEtherGetLinkMode();
void sceNetConfigEtherPostPlugInOutEvent();
void sceNetConfigEtherSetLinkMode();
void sceNetConfigFlushRoute();
void sceNetConfigGetDefaultRoute();
void sceNetConfigGetDefaultRoute6();
void sceNetConfigGetIfaddr();
void sceNetConfigGetIfaddr6();
void sceNetConfigRoutingShowRoutingConfig();
void sceNetConfigRoutingShowtCtlVar();
void sceNetConfigRoutingStart();
void sceNetConfigRoutingStop();
void sceNetConfigSetDefaultRoute();
void sceNetConfigSetDefaultRoute6();
void sceNetConfigSetDefaultScope();
void sceNetConfigSetIfaddr();
void sceNetConfigSetIfaddr6();
void sceNetConfigSetIfmtu();
void sceNetConfigUpInterface();
void sceNetConfigWlanAdhocClearWakeOnWlan();
void sceNetConfigWlanAdhocCreate();
void sceNetConfigWlanAdhocGetWakeOnWlanInfo();
void sceNetConfigWlanAdhocJoin();
void sceNetConfigWlanAdhocLeave();
void sceNetConfigWlanAdhocPspEmuClearWakeOnWlan();
void sceNetConfigWlanAdhocPspEmuGetWakeOnWlanInfo();
void sceNetConfigWlanAdhocPspEmuSetWakeOnWlan();
void sceNetConfigWlanAdhocScanJoin();
void sceNetConfigWlanAdhocSetExtInfoElement();
void sceNetConfigWlanAdhocSetWakeOnWlan();
void sceNetConfigWlanApStart();
void sceNetConfigWlanApStop();
void sceNetConfigWlanBackgroundScanQuery();
void sceNetConfigWlanBackgroundScanStart();
void sceNetConfigWlanBackgroundScanStop();
void sceNetConfigWlanDiagGetDeviceInfo();
void sceNetConfigWlanDiagSetAntenna();
void sceNetConfigWlanGetDeviceConfig();
void sceNetConfigWlanInfraGetRssiInfo();
void sceNetConfigWlanInfraLeave();
void sceNetConfigWlanInfraScanJoin();
void sceNetConfigWlanScan();
void sceNetConfigWlanSetDeviceConfig();
int32_t sceNetConnect(OrbisNetId, const OrbisNetSockaddr*, OrbisNetSocklen_t);
void sceNetControl();
void sceNetDhcpdStart();
void sceNetDhcpdStop();
void sceNetDhcpGetAutoipInfo();
void sceNetDhcpGetInfo();
void sceNetDhcpGetInfoEx();
void sceNetDhcpStart();
void sceNetDhcpStop();
void sceNetDumpAbort();
void sceNetDumpCreate();
void sceNetDumpDestroy();
void sceNetDumpRead();
void sceNetDuplicateIpStart();
void sceNetEpollAbort();
void sceNetEpollControl();
void sceNetEpollCreate();
void sceNetEpollDestroy();
void sceNetEpollWait();
void sceNetErrnoLoc();
int32_t sceNetEtherNtostr(unsigned char* macAddr, char* out, int32_t length);
void sceNetEtherStrton();
void sceNetEventCallbackCreate();
void sceNetEventCallbackDestroy();
void sceNetEventCallbackGetError();
void sceNetEventCallbackWaitCB();
void sceNetFreeAllRouteInfo();
void sceNetGetArpInfo();
int32_t sceNetGetDnsInfo(OrbisNetDnsInfo* info, int32_t flags);
int32_t sceNetGetIfList(enum OrbisNetIfName ifName_num, struct OrbisNetIfEntry* out, int32_t unk);
void sceNetGetIfListOnce();
void sceNetGetIfName();
void sceNetGetIfnameNumList();
int32_t sceNetGetMacAddress(OrbisNetEtherAddr* mac_address, int32_t len);
void sceNetGetMemoryPoolStats();
void sceNetGetNameToIndex();
int32_t sceNetGetpeername(OrbisNetId, OrbisNetSockaddr*, OrbisNetSocklen_t*);
void sceNetGetRandom();
void sceNetGetRouteInfo();
void sceNetGetSockInfo();
void sceNetGetSockInfo6();
int32_t sceNetGetsockname(OrbisNetId, OrbisNetSockaddr*, OrbisNetSocklen_t*);
int32_t sceNetGetsockopt(OrbisNetId, int32_t, int32_t, void*, OrbisNetSocklen_t*);
void sceNetGetStatisticsInfo();
void sceNetGetSystemTime();
uint32_t sceNetHtonl(uint32_t);
uint64_t sceNetHtonll(uint64_t);
uint16_t sceNetHtons(uint16_t);
void sceNetInetNtop();
int32_t sceNetInetPton(int32_t, const char*, void*);
void sceNetInetPtonEx();
int32_t sceNetInit();
void sceNetIoctl();
int32_t sceNetListen(OrbisNetId, int);
void sceNetMemoryAllocate();
void sceNetMemoryFree();
uint32_t sceNetNtohl(uint32_t);
uint64_t sceNetNtohll(uint64_t);
uint16_t sceNetNtohs(uint16_t);
int32_t sceNetPoolCreate(const char *name, int32_t size, int32_t flags);
int32_t sceNetPoolDestroy(int32_t);
void sceNetPppoeStart();
void sceNetPppoeStop();
int32_t sceNetRecv(OrbisNetId, void*, uint64_t, int);
int32_t sceNetRecvfrom(OrbisNetId, void*, uint64_t, int32_t, OrbisNetSockaddr*, OrbisNetSocklen_t*);
int32_t sceNetRecvmsg(OrbisNetId, OrbisNetMsghdr*, int);
int32_t sceNetResolverAbort(OrbisNetId, int32_t flags);
OrbisNetId sceNetResolverCreate(const char *name, int32_t memid, int32_t flags);
int32_t sceNetResolverDestroy(OrbisNetId);
void sceNetResolverGetError();
void sceNetResolverStartAton();
void sceNetResolverStartAton6();
int32_t sceNetResolverStartNtoa(OrbisNetId rid, const char *hostname, OrbisNetInAddr *addr, int32_t timeout, int32_t retry, int32_t flags);
void sceNetResolverStartNtoa6();
void sceNetResolverStartNtoaMultipleRecords();
void sceNetResolverStartNtoaMultipleRecordsEx();
int32_t sceNetSend(OrbisNetId, const void*, uint64_t, int);
int32_t sceNetSendmsg(OrbisNetId, const OrbisNetMsghdr*, int);
int32_t sceNetSendto(OrbisNetId, const void*, uint64_t, int32_t, const OrbisNetSockaddr*, OrbisNetSocklen_t);
void sceNetSetDnsInfo();
void sceNetSetDnsInfoToKernel();
int32_t sceNetSetsockopt(OrbisNetId, int32_t, int32_t, const void*, OrbisNetSocklen_t);
void sceNetShowIfconfig();
void sceNetShowIfconfigWithMemory();
void sceNetShowNetstat();
void sceNetShowNetstatWithMemory();
void sceNetShowPolicy();
void sceNetShowPolicyWithMemory();
void sceNetShowRoute();
void sceNetShowRoute6();
void sceNetShowRouteWithMemory();
int32_t sceNetShutdown(OrbisNetId, int);
OrbisNetId sceNetSocket(const char *, int32_t, int32_t, int);
int32_t sceNetSocketAbort(OrbisNetId, int);
int32_t sceNetSocketClose(OrbisNetId);
void sceNetSyncCreate();
void sceNetSyncDestroy();
void sceNetSyncGet();
void sceNetSyncSignal();
void sceNetSyncWait();
void sceNetSysctl();
void sceNetTerm();
void sceNetThreadCreate();
void sceNetThreadExit();
void sceNetThreadJoin();
void sceNetUsleep();

#ifdef __cplusplus
}
#endif

#endif
