#ifndef _SCE_NP_MANAGER_H_
#define _SCE_NP_MANAGER_H_

#include <stdint.h>
#include <orbis/_types/Np.h>

#ifdef __cplusplus 
extern "C" {
#endif

void _sceNpIpcCreateMemoryFromKernel();
void _sceNpIpcCreateMemoryFromPool();
void _sceNpIpcDestroyMemory();
void _sceNpIpcFreeImpl();
void _sceNpIpcGetNpMemAllocator();
void _sceNpIpcMallocImpl();
void _sceNpIpcReallocImpl();
void _sceNpManagerCreateMemoryFromKernel();
void _sceNpManagerCreateMemoryFromPool();
void _sceNpManagerDestroyMemory();
void _sceNpManagerFreeImpl();
void _sceNpManagerGetNpMemAllocator();
void _sceNpManagerMallocImpl();
void _sceNpManagerReallocImpl();
int32_t sceNpAbortRequest(int32_t req_id);
void sceNpAsmClientGetNpComInfo2();
void sceNpAsmClientGetNpTitleToken();
void sceNpAsmClientGetServiceIdInfo();
void sceNpAsmClientInitialize();
void sceNpCheckCallback();
void sceNpCheckCallbackForLib();
void sceNpCheckNpAvailability();
int32_t sceNpCheckNpAvailabilityA(int32_t req_id, int32_t user_id);
void sceNpCheckNpReachability();
void sceNpCheckPlus();
void sceNpCreateAsyncRequest();
int32_t sceNpCreateRequest();
int32_t sceNpDeleteRequest(int32_t req_id);
void sceNpGetAccountCountry();
void sceNpGetAccountCountryA();
void sceNpGetAccountDateOfBirth();
void sceNpGetAccountDateOfBirthA();
void sceNpGetAccountId();
void sceNpGetAccountIdA();
void sceNpGetAccountLanguage();
void sceNpGetAccountLanguageA();
void sceNpGetGamePresenceStatus();
void sceNpGetGamePresenceStatusA();
int32_t sceNpGetNpId(int32_t user_id, OrbisNpId* np_id);
void sceNpGetNpReachabilityState();
int32_t sceNpGetOnlineId(int32_t user_id, OrbisNpOnlineId* online_id);
void sceNpGetParentalControlInfo();
void sceNpGetParentalControlInfoA();
void sceNpGetState();
void sceNpGetUserIdByAccountId();
void sceNpGetUserIdByOnlineId();
int32_t sceNpHasSignedUp(int32_t user_id, bool* signed_up);
void sceNpIdMapperAbortRequest();
void sceNpIdMapperAccountIdToNpId();
void sceNpIdMapperAccountIdToOnlineId();
void sceNpIdMapperCreateRequest();
void sceNpIdMapperDeleteRequest();
void sceNpIdMapperNpIdToAccountId();
void sceNpIdMapperOnlineIdToAccountId();
void sceNpInGameMessageAbortHandle();
void sceNpInGameMessageCreateHandle();
void sceNpInGameMessageDeleteHandle();
void sceNpInGameMessageInitialize();
void sceNpInGameMessagePrepare();
void sceNpInGameMessagePrepareA();
void sceNpInGameMessageSendData();
void sceNpInGameMessageSendDataA();
void sceNpInGameMessageTerminate();
int32_t sceNpIntCheckPlus(int32_t req_id, OrbisNpIntCheckPlusParameter* param, OrbisNpIntCheckPlusResult* result);
int32_t sceNpManagerIntAbortRequest(int32_t req_id);
int32_t sceNpManagerIntAddPlusMemberTypeCallback(int32_t user_id, OrbisNpManagerPlusMemberTypeCallback cb_func, void* user_arg);
int32_t sceNpManagerIntBindOfflineAccountId(int32_t user_id, OrbisNpOfflineAccountId* offline_account_id, bool is_adult);
void sceNpManagerIntCheckGameNpAvailability();
int32_t sceNpManagerIntCheckGameNpAvailabilityByPid(int32_t req_id, int32_t pid, int32_t user_id);
int32_t sceNpManagerIntClearOnlineIdChangeFlag(int32_t user_id);
int32_t sceNpManagerIntClearParentalControlInfoSubAccount();
void sceNpManagerIntClearUsedFlag();
int32_t sceNpManagerIntCreateLoginContext(int32_t user_id);
int32_t sceNpManagerIntCreateLoginRequest(int32_t login_ctx_id);
int32_t sceNpManagerIntCreateRequest();
int32_t sceNpManagerIntDeleteLoginContext(int32_t login_ctx_id);
int32_t sceNpManagerIntDeleteRequest(int32_t req_id);
int32_t sceNpManagerIntGetAccountCountry(OrbisNpOnlineId* online_id, OrbisNpCountryCode* country_code);
int32_t sceNpManagerIntGetAccountCountryA(int32_t user_id, OrbisNpCountryCode* country_code);
int32_t sceNpManagerIntGetAccountDateOfBirth(OrbisNpOnlineId* online_id, OrbisNpDate* date_of_birth);
int32_t sceNpManagerIntGetAccountDateOfBirthA(int32_t user_id, OrbisNpDate* date_of_birth);
int32_t sceNpManagerIntGetAccountId(int32_t user_id, uint64_t* account_id);
int32_t sceNpManagerIntGetAccountLanguage(int32_t req_id, OrbisNpOnlineId* online_id, OrbisNpLanguageCode* lang_code);
int32_t sceNpManagerIntGetAccountLanguageA(int32_t req_id, int32_t user_id, OrbisNpLanguageCode* lang_code);
int32_t sceNpManagerIntGetAccountNpEnv(int32_t user_id, OrbisNpManagerNpEnv* np_env);
int32_t sceNpManagerIntGetAccountType(int32_t user_id, OrbisNpAccountType* account_type);
void sceNpManagerIntGetActiveSigninState();
int32_t sceNpManagerIntGetAuthorizationCode(int32_t req_id, OrbisNpOnlineId* online_id, OrbisNpClientId* client_id, char* redirect_uri, char* scope, OrbisNpAuthorizationCode* auth_code);
int32_t sceNpManagerIntGetAuthorizationCodeA(int32_t req_id, int32_t user_id, OrbisNpClientId* client_id, char* redirect_uri, char* scope, OrbisNpAuthorizationCode* auth_code);
int32_t sceNpManagerIntGetAuthorizationCodeWithPsnoUri(int32_t req_id, int32_t user_id, char* psno_uri, char* redirect_uri, int32_t size);
void sceNpManagerIntGetAuthorizationCodeWithRedirectUri();
int32_t sceNpManagerIntGetAuthServerErrorFlag(int32_t user_id, uint32_t* error_flag);
int32_t sceNpManagerIntGetClientCredentialAccessToken(int32_t req_id, char* scope, OrbisNpAccessToken* access_token);
void sceNpManagerIntGetGameTitleBanInfo();
void sceNpManagerIntGetGameTitleToken();
void sceNpManagerIntGetGameVshToken();
int32_t sceNpManagerIntGetLastAccountLanguage(int32_t user_id, OrbisNpLanguageCode* lang_code);
void sceNpManagerIntGetMAccountId();
int32_t sceNpManagerIntGetNpEnv(OrbisNpManagerNpEnv* np_env);
void sceNpManagerIntGetNpId();
int32_t sceNpManagerIntGetNpIdSdk(int32_t user_id, OrbisNpId* np_id);
int32_t sceNpManagerIntGetOfflineAccountId(int32_t user_id, OrbisNpOfflineAccountId* offline_account_id, bool* is_adult);
int32_t sceNpManagerIntGetOnlineIdChangeFlag(int32_t user_id, bool* is_online_id_changed);
int32_t sceNpManagerIntGetOnlineIdInternal(int32_t user_id, OrbisNpOnlineId* online_id);
int32_t sceNpManagerIntGetOnlineIdSdk(int32_t user_id, OrbisNpOnlineId* online_id);
int32_t sceNpManagerIntGetParentalControlFlag(int32_t user_id, OrbisNpParentalControlInfo* info);
int32_t sceNpManagerIntGetParentalControlInfo(int32_t req_id, OrbisNpOnlineId* online_id, uint8_t* age, OrbisNpParentalControlInfo* info);
int32_t sceNpManagerIntGetParentalControlInfoA(int32_t req_id, int32_t user_id, uint8_t* age, OrbisNpParentalControlInfo* info);
void sceNpManagerIntGetParentalControlInfoNB();
int32_t sceNpManagerIntGetPlusMemberType(int32_t req_id, int32_t user_id, OrbisNpPlusMemberType* plus_member_type);
int32_t sceNpManagerIntGetPlusMemberTypeNB(int32_t user_id, OrbisNpPlusMemberType* plus_member_type);
int32_t sceNpManagerIntGetServerError(int32_t req_id, OrbisNpManagerServerError* server_error);
int32_t sceNpManagerIntGetSigninState(int32_t user_id, OrbisNpSigninState* state);
void sceNpManagerIntGetTicket();
void sceNpManagerIntGetTicketNB();
int32_t sceNpManagerIntGetTitleTokenWithCheck(int32_t req_id, int32_t pid, int32_t user_id, OrbisNpTitleId* title_id, OrbisNpTitleToken* title_token);
int32_t sceNpManagerIntGetUserIdByAccountId(uint64_t account_id, int32_t* user_id);
int32_t sceNpManagerIntGetUserIdByOfflineAccounId(OrbisNpOfflineAccountId* offline_account_id, int32_t* user_id);
int32_t sceNpManagerIntGetUserIdByOnlineId(OrbisNpOnlineId* online_id, int32_t* user_id);
void sceNpManagerIntGetUserList();
void sceNpManagerIntGetUserNum();
void sceNpManagerIntGetUserState();
int32_t sceNpManagerIntGetVshAccessToken(int32_t req_id, int32_t user_id, OrbisNpAccessToken* access_token);
int32_t sceNpManagerIntGetVshAccessTokenWithCheck(int32_t req_id, int32_t pid, int32_t user_id, OrbisNpAccessToken* access_token);
int32_t sceNpManagerIntGetVshClientId(OrbisNpClientId* client_id);
void sceNpManagerIntGetVshToken();
void sceNpManagerIntGetVshTokenNB();
void sceNpManagerIntIsServerMaintenanceError();
int32_t sceNpManagerIntIsSubAccount(int32_t user_id, bool* is_sub_account);
int32_t sceNpManagerIntIsTemporarySignout(int32_t user_id, bool* temp_signout);
bool sceNpManagerIntIsUnregisteredClientError(int32_t error_code);
int32_t sceNpManagerIntLoginAddJsonInfo(int32_t login_ctx_id, char* sso_cookie, char* json_user_info);
int32_t sceNpManagerIntLoginAuthenticate(int32_t login_req_id, char* request_json);
int32_t sceNpManagerIntLoginBind(int32_t login_ctx_id, int32_t user_id, bool is_email_verified);
void sceNpManagerIntLoginCheckSignin();
int32_t sceNpManagerIntLoginGet2svInfo(int32_t login_ctx_id, OrbisNp2svInfo* info);
int32_t sceNpManagerIntLoginGetAccessToken(int32_t login_req_id, OrbisNpAccessToken* access_token);
int32_t sceNpManagerIntLoginGetAccessTokenViaImplicitFlow(int32_t login_req_id, OrbisNpClientId* client_id, char* redirect_uri, char* scope, OrbisNpAccessToken* access_token, OrbisNpIdToken* id_token);
int32_t sceNpManagerIntLoginGetAccountId(int32_t login_ctx_id, uint64_t* account_id);
int32_t sceNpManagerIntLoginGetAuthenticateResponse(int32_t login_req_id, char* response_json, int32_t response_json_size);
int32_t sceNpManagerIntLoginGetAuthorizationCode(int32_t login_req_id, OrbisNpClientId* client_id, char* redirect_uri, char* scope, OrbisNpAuthorizationCode* code);
int32_t sceNpManagerIntLoginGetDeviceCodeInfo(int32_t login_req_id, OrbisNpDeviceName* device_name, OrbisNpDeviceCodeInfo* device_code_info);
int32_t sceNpManagerIntLoginGetEmail(int32_t login_ctx_id, OrbisNpLoginId* login_id);
int32_t sceNpManagerIntLoginGetOnlineId(int32_t login_ctx_id, OrbisNpOnlineId* online_id);
int32_t sceNpManagerIntLoginGetUserId(int32_t login_ctx_id, int32_t* user_id);
int32_t sceNpManagerIntLoginParseJsonUserInfo(char* json_user_info, OrbisNpManagerJsonUserInfo* user_info);
int32_t sceNpManagerIntLoginResetSsoToken(int32_t login_ctx_id);
int32_t sceNpManagerIntLoginRevalidatePassword(int32_t login_req_id, OrbisNpPassword* password);
int32_t sceNpManagerIntLoginSetAccountInfo(int32_t login_ctx_id, uint64_t account_id, OrbisNpOnlineId* online_id);
int32_t sceNpManagerIntLoginSetSsoToken(int32_t login_ctx_id, OrbisNpSsoToken* sso_token);
int32_t sceNpManagerIntLoginSignin(int32_t login_req_id);
int32_t sceNpManagerIntLoginValidateCredential(int32_t login_req_id, OrbisNpLoginId* login_id, OrbisNpPassword* password, bool validate_only);
int32_t sceNpManagerIntLoginValidateKratosAuthCode(int32_t login_req_id, OrbisNpAuthorizationCode* code, OrbisNpKratosRedirectUri* redirect_uri);
int32_t sceNpManagerIntLoginVerifyDeviceCode(int32_t login_req_id);
int32_t sceNpManagerIntPfAuth(int32_t req_id, bool updates_user_clock);
int32_t sceNpManagerIntRemovePlusMemberTypeCallback(int32_t cb_id);
int32_t sceNpManagerIntRevalidatePassword(int32_t req_id, int32_t user_id, OrbisNpPassword* password);
void sceNpManagerIntSetTimeout();
int32_t sceNpManagerIntSignout(int32_t user_id);
int32_t sceNpManagerIntTemporarySignout(int32_t user_id);
int32_t sceNpManagerIntUnbindOfflineAccountId(int32_t user_id);
int32_t sceNpManagerIntUpdateVshToken(int32_t req_id, int32_t user_id, OrbisNpAccessToken* access_token);
bool sceNpManagerIntWebLoginRequired(int32_t return_code);
void sceNpManagerPrxStartVsh();
void sceNpManagerUtilConvertJidToNpId();
void sceNpManagerUtilConvertNpIdToJid();
void sceNpNotifyPlusFeature();
void sceNpPollAsync();
void sceNpPushInit();
void sceNpPushIntBeginInactive();
void sceNpPushIntEndInactive();
void sceNpPushIntGetConnectionState();
void sceNpRegisterGamePresenceCallback();
void sceNpRegisterGamePresenceCallbackA();
void sceNpRegisterNpReachabilityStateCallback();
void sceNpRegisterPlusEventCallback();
void sceNpRegisterStateCallback();
void sceNpRegisterStateCallbackA();
void sceNpServiceClientInit();
void sceNpServiceClientTerm();
void sceNpSetContentRestriction();
void sceNpSetGamePresenceOnlineA();
int32_t sceNpSetNpTitleId(OrbisNpTitleId* title_id, OrbisNpTitleSecret* title_secret);
void sceNpSetTimeout();
void sceNpUnregisterNpReachabilityStateCallback();
void sceNpUnregisterPlusEventCallback();
void sceNpUnregisterStateCallback();
void sceNpUnregisterStateCallbackA();
void sceNpWaitAsync();

#ifdef __cplusplus
}
#endif
#endif